version: '3.9'
services:
  kongdb:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "kong"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_PG_HOST=kongdb
      - KONG_PG_PASSWORD=1234
    depends_on:
      - kongdb
  
  kong:
    image: kong:latest
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kongdb
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=1234
      - KONG_PROXY_LISTEN= 0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    depends_on:
      - kongdb
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:1234@kongdb:5432/konga"
    restart: on-failure
    depends_on:
      - kongdb

  konga:
    image: pantsel/konga:latest
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:1234@kongdb:5432/konga
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
    
  kongdeck:
    image: kong/deck

networks:
  default:
    name: kong_net
    external: true

volumes:
  pg-data: