_format_version: "1.1"
consumers:
- acls:
  - group: g1
  jwt_secrets:
  - algorithm: HS256
    key: admin
    secret: admin
  username: user
services:
- connect_timeout: 60000
  enabled: true
  host: user_app
  name: user_service
  path: /
  port: 5000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: OpenAccount
    path_handling: v1
    paths:
    - /OpenAccount
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - GET
    name: greetting
    path_handling: v1
    paths:
    - /Hello
    plugins:
    - config:
        allow:
        - g1
        deny: null
        hide_groups_header: false
      enabled: true
      name: acl
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: kid
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
