POST http://localhost:8000/OpenAccount
content-type: application/json

{
    "username": "ggg",
    "password":"1234"
}

###
GET http://localhost:8000/Hello

###
POST http://localhost:8000/Login
content-type: application/json

{
    "username": "gg",
    "password":"1234"
}