POST http://localhost:5000/OpenAccount
content-type: application/json

{
    "username": "ggg",
    "password":"1234"
}

###
GET http://localhost:5000/Hello

###
POST http://localhost:5000/Login
content-type: application/json

{
    "username": "ggg",
    "password":"1234"
}

###
GET  http://localhost:5000/Logout