version: '3.9'
services:
  database:
    image: mariadb
    ports:
      - 4306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    networks:
      - db
  
  user_app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - kong
      - db
    

networks:
  db:
  kong:
    name: kong_net
    external: true