version: '3.9'
services:
  subjectdb:
    image: mariadb
    container_name: subject_db
    ports:
      - 4307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    networks:
      - db
  
  app:
    build: .
    ports:
      - 5001:5001
    depends_on:
      subjectdb:
        condition: service_healthy
    links:
      - "subjectdb:database"
    networks:
      - kong
      - db
    

networks:
  db:
  kong:
    name: kong_net
    external: true
